const options = [
	{ label: "Português", value: "portugues" },
	{ label: "Matemática", value: "matematica" },
	{ label: "História", value: "historia" },
	{ label: "Geografia", value: "geografia" },
	{ label: "Ciências", value: "ciencias" },
	{ label: "Artes", value: "artes" },
	{ label: "Educação Física", value: "educacaofisica" },
	{ label: "Inglês", value: "ingles" },
	{ label: "Filosofia", value: "filosofia" },
	{ label: "Sociologia", value: "sociologia" },
	{ label: "Química", value: "quimica" },
	{ label: "Física", value: "fisica" },
	{ label: "Biologia", value: "biologia" },
	{ label: "Informática", value: "informatica" },
	{ label: "Espanhol", value: "espanhol" },
	{ label: "Música", value: "musica" },
	{ label: "Literatura", value: "literatura" },
	{ label: "Redação", value: "redacao" },
	{ label: "Outros", value: "outros" },
	{ label: "Informática", value: "informatica" },
	{ label: "Eletrotécnica", value: "eletrotecnica" },
	{ label: "Mecânica", value: "mecanica" },
	{ label: "Eletricidade", value: "eletricidade" },
	{ label: "Eletrônica", value: "eletronica" },
	{ label: "Automação", value: "automacao" },
	{ label: "Telecomunicações", value: "telecomunicacoes" },
	{ label: "Construção Civil", value: "construcaocivil" },
	{ label: "Desenho Técnico", value: "desenhotecnico" },
	{ label: "Multimídia", value: "multimidia" },
	{ label: "Contabilidade", value: "contabilidade" },
	{ label: "Administração", value: "administracao" },
	{ label: "Logística", value: "logistica" },
	{ label: "Redes de Computadores", value: "redescomputadores" },
	{ label: "Manutenção de Informática", value: "manutencaoinformatica" },
	{ label: "Desenvolvimento de Sistemas", value: "desenvolvimento" },
	{ label: "Agroindústria", value: "agroindustria" },
	{ label: "Meio Ambiente", value: "meioambiente" },
];

export const GET = async () => {
	return options;
};
